### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by RK-BAKU** [yl4579/PL-BERT#10]
@yl4579 first of all - thank you for your great work!
I'm unable to train model from scratch using provided notebook.
Kindly provide some hint on this issue.

`Start training...
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    notebook_launcher(train, args=(), num_processes=1, use_port=33389)
  File "/lib/python3.8/site-packages/accelerate/launchers.py", line 156, in notebook_launcher
    function(*args)
  File "train.py", line 139, in train
    loss_token /= sizes
ZeroDivisionError: division by zero`

**Comment by yl4579** [comment]
For some reason `masked_indices` are empty for all samples in your batch. Can you please check if your masking probability is set to nonzero?

**Comment by RK-BAKU** [comment]
@yl4579 

Can you please provide a hint on possible reasons of masked_indices being empty?
I haven't tuned any config params just used your code as is except the dataset, which I believe is ok.

**Comment by yl4579** [comment]
It seems like your dataset is broken. Can you check if your dataset makes sense? What does your data sample look like?
