### ISSUE TITLE
UnicodeDecodeError while processing shards

### ISSUE THREAD

**Issue by NikitaKononov** [yl4579/PL-BERT#13]
Hello
I am trying to reproduce your preprocessing and training processes with wikipedia en dataset for better understanding

But I get decoding error while shard phonemizing
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 6: invalid start byte

Have you encountered same problem?

i've tried this, but it doesn't help
phonemize(t['text'].encode('utf-8', errors='ignore').decode('utf-8'), global_phonemizer, tokenizer)

**Comment by yl4579** [comment]
Does this happen to all of them or only one of the subprocesses? Some shards are expected to fail with various errors, but it should be fine if only <1% of the shards fail, and you can always redo it until all are succeed.

**Comment by NikitaKononov** [comment]
> Does this happen to all of them or only one of the subprocesses? Some shards are expected to fail with various errors, but it should be fine if only <1% of the shards fail, and you can always redo it until all are succeed.

All of them, I had restarted the preprocessing procedure many times and none of the shards were processed successfully

**Comment by yl4579** [comment]
What dataset are you using?

**Comment by NikitaKononov** [comment]
> What dataset are you using?

Same version of Wikipedia en

**Comment by yl4579** [comment]
Very weird, have you tried to add a print line in `phonemize` and see exactly what the text looks like?

**Comment by NikitaKononov** [comment]
> Very weird, have you tried to add a print line in `phonemize` and see exactly what the text looks like?

It's weird, I agree
Text looks normal
It happens only in multithread mode
When I run same code in one thread (simple for loop) - all is ok...
Tried different multithreading tools - result is the same

**Comment by yl4579** [comment]
Likely some nasty bugs with the multiprocessing library in your base system (not Python library but your system library) that causes memory leaks so it slides in a few invalid characters. You may have to reinstall your system to fix this.
