### ISSUE TITLE
Reproduce demo samples quality

### ISSUE THREAD

**Issue by teopapad92** [yl4579/PL-BERT#17]
hello,

Thanks for you contribution!

I want to ask how can I reproduce the quality of the sound for your out of distribution details?

After playing around with it, I figured it matters a lot which input audio I have to use as reference embedding. 

Do you have 1 that works best in general? Or we need a different one for different scenarios?

**Comment by yl4579** [comment]
That’s the biggest problem of StyleTTS that was addressed in StyleTTS 2 with a diffusion model to produces the most suitable style based on the text. See https://arxiv.org/abs/2306.07691

The demo uses a SentenceBERT that extracts all the embeddings of texts in the training data, finds the closest one of the input text, and use that as the reference.
