### ISSUE TITLE
Add PL-BERT to SVS

### ISSUE THREAD

**Issue by francqz31** [yl4579/PL-BERT#19]
I wanted to add pl-bert to https://github.com/zhangyongmao/VISinger2 and retrain it from scratch for comparison
But i don't have any idea on where to start . like what should i replace because it is not clear tbh.
like should i start here 👇 ? and what should i do?
https://github.com/zhangyongmao/VISinger2/blob/master/egs/visinger2/models.py

if you can guide me i would appreciate it.

I will report the difference back to you if it is big!

**Comment by yl4579** [comment]
I'm not so sure why you want to add PL-BERT to SVS. Does a language model help with singing? I think anyone can sing in any language even though you don't speak that language, so I don't feel like it is not relevant. Also, the pre-trained model is in English and it seems visinger2 is Chinese, so I don't think it would be compatible. You may have to train your own PL-BERT in Chinese instead.

But if you really want to add it to visinger2, you can just replace the phoneme embedding with PL-BERT here: https://github.com/zhangyongmao/VISinger2/blob/master/egs/visinger2/models.py#L103C10-L103C20

**Comment by yl4579** [comment]
OK this is interesting because I don't do singing synthesis. Thanks for sharing this information. I can hear that the durations are quite different, and I thought the duration was actually fixed by the duration of the notes for singing synthesis. It is actually the same as speech synthesis.
