### ISSUE TITLE
When will the code be publicly available?

### ISSUE THREAD

**Issue by TinaChen95** [yl4579/PL-BERT#2]
Thanks for your great work. Just wondering is there any plan for code public?
Also, before code are publicly available, is there any suggests for pretrain bert on TTS tasks?

**Comment by yl4579** [comment]
I'm currently testing the code for StyleTTS-VC, once it is done I'll make the training pipeline available.

**Comment by TinaChen95** [comment]
Thanks for reply. Looking forward to it. :)
