### ISSUE TITLE
PL-BERT on chinese 

### ISSUE THREAD

**Issue by bobo-paopao** [yl4579/PL-BERT#20]
Hello, I would like to ask if the PL-Bert pre-training model here can be directly used on Chinese tts.

**Comment by yihuitang** [comment]
Unfortunately, no. You'll need to train your own model. I don't know how to though :-(

**Comment by bobo-paopao** [comment]
I got it, thank you~have a good night!

**Comment by yl4579** [comment]
I may release the code for multilingual preprocessing and pre-trained model in Chinese, English and Japanese later when I get time.

**Comment by JohnHerry** [comment]
> You actually can use it directly for Chinese TTS if you have enough data, but I may release the code for multilingual preprocessing and pre-trained model in Chinese, English and Japanese later when I get time.

Good news! Thanks for the coming sharing
