### ISSUE TITLE
masked_index is empty in train_loader

### ISSUE THREAD

**Issue by tekinek** [yl4579/PL-BERT#23]
Thank you for your great work!  

I am trying to train a PL_Bert for new language, but I'am not sure if it is a bug, the `masked_index  `is always empty when I enumerate the `train_loader`.  I've seen the `masked_index `was populated before it is re-initialized by the following code:

https://github.com/yl4579/PL-BERT/blob/3bc52144bdb1dd8bc2167899ebeac1718c3dde6f/dataloader.py#L92

Is `masked_index `used when only `mel_length > self.max_mel_length`?   To me, `masked_index = []`  should be placed under the  `if `statement at line 90.

**Comment by yl4579** [comment]
It indeed is a bug if all of your phonemes lengths are shorter than 512. I should fixed by adding an else line and set `masked_index` as `masked_idx` instead. Could you please try this fix and see if it produces correct results?

**Comment by tekinek** [comment]
> It indeed is a bug if all of your phonemes lengths are shorter than 512. I should fixed by adding an else line and set `masked_index` as `masked_idx` instead. Could you please try this fix and see if it produces correct results?

It works now. I think it reasly is a bug that alwasy makes `masked_index ` cleared when the length of phonemes is shorter than 512. 

Another bug seems to be with `loss_token /= sizes` in training fuction, which raises zero-devision error at some point of training.

**Comment by yl4579** [comment]
Could you make a PR for your change? I don’t know where the second issue is.

**Comment by tekinek** [comment]
> Could you make a PR for your change? I don’t know where the second issue is.

<img width="696" alt="bug1" src="https://github.com/yl4579/PL-BERT/assets/68597606/a060f3ab-b3f2-4e68-bb62-18a7806d7761">

It is in train.ipynb / tain(), the last line of obove code snippet. `sizes `could be 0 after the loop.

**Comment by tekinek** [comment]
Sorry, I got another problem with my training:  the size my vocab is more than 500k (number of tokens in the `token_map.pkl`) and I have two GPU cards each with 24G of memory. Now I am having out of memory issue even if the batch size is less then 16. Any solution for this?

**Comment by yl4579** [comment]
If the vocab size is this big, I don't think you can easily train it with only two cards. You may want to retokenize them using BPE tokenizer to reduce the vocab size and use sigmoid to predict multiple classes instead (so each phoneme could correspond to multiple tokens, but you can predict each of them using sigmoid).

**Comment by tekinek** [comment]
> If the vocab size is this big, I don't think you can easily train it with only two cards. You may want to retokenize them using BPE tokenizer to reduce the vocab size and use sigmoid to predict multiple classes instead (so each phoneme could correspond to multiple tokens, but you can predict each of them using sigmoid).

Thanks,  let me try to reduce the vocab size.

**Comment by yl4579** [comment]
Cases also don't matter so you can do uncasesd too.

**Comment by tosunozgun** [comment]
i try to train pl-bert for differen languages and getting errors same with @tekinek.

**Comment by yl4579** [comment]
@tosunozgun I think I have fixed it. Could you please try it again?

**Comment by tosunozgun** [comment]
@yl4579 yeap i can train it now thanks for quick response.

**Comment by tekinek** [comment]
> i try to train pl-bert for differen languages and getting errors same with @tekinek.

Happy to hear you can train it now. If it is for a new language, seems extra cares are needed as this repo is not multiliangual-ready. 

Does defaul tokenizer (transfo-xl-wt103) support your language? looks like it tokenizes well many languages where words are space separeted, but these words  may not be in its vocab, so most of the `inputs_ids `turn out to be `<unk>`.  (this is the is case withmy language). So you need to make sure you have correct ids for your tokens.

Now the very large vocab size is an issue for me, because the model directly predicts the word which makes it memory hungry.

**Comment by yl4579** [comment]
It could be fixed by using BPE tokenizers and tokenize each word separately. You may get multiple tokens for a single word, so you can sigmoid the output `[1, vocab_size]` vector and for each token that the phoneme’s corresponding grapheme matches, you maximize it to 1 and otherwise 0 (multi-label classification).

**Comment by tekinek** [comment]
> It could be fixed by using BPE tokenizers and tokenize each word separately. You may get multiple tokens for a single word, so you can sigmoid the output `[1, vocab_size]` vector and for each token that the phoneme’s corresponding grapheme matches, you maximize it to 1 and otherwise 0 (multi-label classification).

Thanks you!  I wil try.  It would be greately appriciated if you update the repo with bpe support when you are available before I make it work:)
