### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length

### ISSUE THREAD

**Issue by dsplog** [yl4579/PL-BERT#30]
when trying to do the preprocessing on malayalam dataset, saw the following error 

> Token indices sequence length is longer than the specified maximum sequence length for this model (4377 > 512). Running this sequence through the model will result in indexing errors

quite likely is happening because the tokenizer 'bert-base-multilingual-cased' is doing mostly 2-character  or so tokenization

```
>>> from transformers import BertTokenizer
>>> tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
>>> text = 'ദേശീയോദ്യാനങ്ങൾ സംരക്ഷിതപ്രദേശങ്ങളാണ്.'
>>> words = tokenizer.tokenize(text)
>>> print(words)
['ദ', '##േശീയ', '##ോ', '##ദ്', '##യ', '##ാന', '##ങ്ങൾ', 'സ', '##ം', '##ര', '##ക്', '##ഷ', '##ി', '##ത', '##പ്', '##ര', '##ദ', '##േ', '##ശ', '##ങ്', '##ങ', '##ളാണ്', '.']
```

which parameter to change  in the config to handle this?

`    max_mel_length: 512 # max phoneme length
`
or 

`    max_position_embeddings: 512
`
?

**Comment by yl4579** [comment]
No, it comes from `max_position_embeddings = 512`. If you want to train models with longer input, you will have to set `max_position_embeddings` larger than 512.
