### ISSUE TITLE
preprocess error

### ISSUE THREAD

**Issue by 2319183863** [yl4579/PL-BERT#31]
Hi, do you know why a error occur when I preprocess the data
![image](https://github.com/yl4579/PL-BERT/assets/49605018/8906e2e7-2b4f-4196-90bb-822b416b0ad5)

**Comment by yl4579** [comment]
It seems it's the same issue as #21

**Comment by 2319183863** [comment]
> It seems it's the same issue as #21

Thank you, this problem is solved.
