### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by 2319183863** [yl4579/PL-BERT#34]
Hello, do you know why I made this mistake during training?
![image](https://github.com/yl4579/PL-BERT/assets/49605018/79e05f68-bc90-4a8f-99f2-5f5596803efc)

**Comment by yl4579** [comment]
It seems the masked indices are out of index. Could you make sure they are within the length of text input in the dataloader?

**Comment by WelkinYang** [comment]
Please modify the vocab_size of MultiTaskModel to increase by at least 1 from what it is currently, as the range of classification loss does not include the number max([m['token'] for m in token_maps.values()]) itself, so there will be a problem with the range of classification loss.
