### ISSUE TITLE
Modify the dataloader of Chinese PL-Bret

### ISSUE THREAD

**Issue by Sachiosharato** [yl4579/PL-BERT#36]
I encountered a problem when modifying the dataloader. What is the token_map of the Chinese data in the dataloader? I cannot understand what the "token" in the token_map used to process English data means, and what the corresponding "token" in Chinese is. What is the thing. If possible, could you please give me the code of the dataloader you use to process Chinese data?

**Comment by Sachiosharato** [comment]
`words = [self.token_maps[w]['token'] for w in words]`
what that code mean in Chinese data

**Comment by yl4579** [comment]
Sorry for the late reply. I was quite busy recently. This pipeline doesn't work for Chinese PL-BERT unfortunately. You may want to refer to #14 and https://github.com/yl4579/StyleTTS2/issues/70 for more information.
