### ISSUE TITLE
Proper format for dataset

### ISSUE THREAD

**Issue by rajdeep1337** [yl4579/PL-BERT#38]
I want to train my own PL-bert model, but am unsure in what format the dataset needs to be. Could you please shed some lights on this? Thanks!

**Comment by yl4579** [comment]
Sorry for the late reply. I was quite busy recently. The format is basically the pair `(phonemes, grapheme token)`. You can refer to this multilingual PL-BERT dataset as an example: https://huggingface.co/datasets/styletts2-community/multilingual-pl-bert
