### ISSUE TITLE
Deviation on using some other BERT model

### ISSUE THREAD

**Issue by Pranjalya** [yl4579/PL-BERT#4]
Thank you for your work, @yl4579 !
I had a question, if we use some other sort of BERT, which have better context modeling, what are your thoughts on the level of improvement we can achieve? 
Also, if possible, it would be great if you can share some insight regarding releasing of the code.
This looks very promising, though.

Regards,
Pranjalya

**Comment by yl4579** [comment]
Not sure what you mean by other sorts of BERT. Maybe you can refer to the introduction section of my paper and MP-BERT paper? 

As for the code, I will try to release the training and data preparation code and the pre-trained model by this week.

**Comment by WhiteFu** [comment]
I am looking forward to it and thank you for your sharing:)
