### ISSUE TITLE
Question regarding train.ipynb - num_tokens

### ISSUE THREAD

**Issue by jav-ed** [yl4579/PL-BERT#41]
see: https://github.com/yl4579/PL-BERT/blob/main/train.ipynb

```py
bert = AlbertModel(albert_base_configuration)
bert = MultiTaskModel(bert, 
                      num_vocab=max([m['token'] for m in token_maps.values()]), 
                      num_tokens=config['model_params']['vocab_size'],
                      hidden_size=config['model_params']['hidden_size'])
```

`num_tokens=config['model_params']['vocab_size'] = 178`. However, if you view the `len(dicts) = 177`

```py
_pad = "$"
_punctuation = ';:,.!?¡¿—…"«»“” '
_letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
_letters_ipa = "ɑɐɒæɓʙβɔɕçɗɖðʤəɘɚɛɜɝɞɟʄɡɠɢʛɦɧħɥʜɨɪʝɭɬɫɮʟɱɯɰŋɳɲɴøɵɸθœɶʘɹɺɾɻʀʁɽʂʃʈʧʉʊʋⱱʌɣɤʍχʎʏʑʐʒʔʡʕʢǀǁǂǃˈˌːˑʼʴʰʱʲʷˠˤ˞↓↑→↗↘'̩'ᵻ"

# Export all symbols:
symbols = [_pad] + list(_punctuation) + list(_letters) + list(_letters_ipa)

letters = list(_letters) + list(_letters_ipa)

dicts = {}
for i in range(len((symbols))):
    dicts[symbols[i]] = i

```
So, we have only 177 unique phoneme character, based in the length of the dict. We would have a length of 178, if we would count the duplicate sign in _letters_ipa twice.  Maybe there is a special phoneme that is not stored inside the dicts, that I am missing here? So the question is, why do we have num_token = 178 and not 177?

Thank you for effort

**Comment by tekinek** [comment]
@jav-ed 
I see that the symble "'" is duplicatied in `_letters_ipa`. As long as the `dicts ` is used for phoneme2id mapping everywhere, it does not make problem.

**Comment by jav-ed** [comment]
@tekinek 
Sorry, I do not understand this. From what I understand, the number of tokens (num_tokens) is a parameter that decides how many phonemes the model will try to learn. The higher the number (num_tokens) the more phoneme characters, the model will try to learn. We can put it also in another way, the higher the number of tokens, the more flexibility the model will have to learn something. If something is only linear, but we gave it the freedom of a let's say cubic (x^3) function then, within the range of the training data, we have a very good interpolation. However, outside the seen training data, the extrapolation can be assumed to be terrible.

So, allowing the model too much freedom could have negative consequences.

**Comment by jav-ed** [comment]
By the way, @tekinek yes are right with the found duplicate symbol

**Comment by yl4579** [comment]
Yes, setting 178 is to prevent out of index issue (even though there are only 177 symbols and one duplicate token). We can repupose some tokens (for example, the last 177th token) for some other use later if we need it.
