### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by rumbleFTW** [yl4579/PL-BERT#44]
I am trying to train my own PL-BERT model on my [indic subset](https://huggingface.co/datasets/rumbleFTW/indic-pl-bert) of the [multilingual-pl-bert](https://huggingface.co/datasets/styletts2-community/multilingual-pl-bert) dataset. But I am encountering this issue:

![image](https://github.com/yl4579/PL-BERT/assets/85807431/9f3458ca-e42b-4643-a23d-1877898e3d2d)

This occurs when `next(enumerate(train_loader))` is called. Any idea on how to fix this?

**Comment by SanketDhuri** [comment]
did you figured out solution for this error ?
or it's still a problem

**Comment by SoshyHayami** [comment]
the column for input ids is a list, you need to either modify your code to consider this or remove the list bracket.

**Comment by kdcyberdude** [comment]
Hi @SoshyHayami,

> the column for input ids are listed, that's why it throws an error. you need to either modify your code to consider this or remove the list bracket. 

Can you elaborate on this a bit more? I am not able to fix this.
