### ISSUE TITLE
What is the effect of punctuations in text in PL-BERT

### ISSUE THREAD

**Issue by JohnHerry** [yl4579/PL-BERT#7]
Hi, yl
    I did not see any description in the paper, about the punctuations in the text. How much effect did they taken in the success of PL-BERT? can PL-BERT help synthesis those long sentences with nested subordinate clauses without punctuations inside well?

    I have another question that maybe out of range. Whyt this paper choose to use StyleTTS as backbone of the research, which need a style reference audio that seems weird in common TTS products?

**Comment by yl4579** [comment]
It does. You can listen to the difference between w/ PL-BERT and w/o PL-BERT on the demo page: [https://pl-bert.github.io/](https://pl-bert.github.io/), especially the abstract. You can also try it yourself, the pre-trained models and the inference code are available directly in README. 

As for why StyleTTS was used, it was the state-of-the-art on LJSpeech at the time this research was done (last year around this time), so it would of course be interesting to see how much BERT can do for SOTA in this field. 

I think it is indeed weird that you need a reference for StyleTTS, but it is just one step toward something more general (how to model the speech style in TTS). Stay tuned for StyleTTS 2 which is a new human-level TTS model that outperforms NaturalSpeech and even the ground truth without any need for reference audio. I will preprint the paper soon in the next couple of weeks and release the soon in around July or August.
