### ISSUE TITLE
Use with other TTS?

### ISSUE THREAD

**Issue by godspirit00** [yl4579/PL-BERT#8]
Hi @yl4579 !
Thanks for the great work!
I'm working on a TTS application based on VITS, and I'd like to improve the natualness of speech, and I came across here.
You mentioned [here](https://github.com/yl4579/PL-BERT/issues/3#issuecomment-1480346551) that you had tested PL-BERT with VITS. Could you please explain a bit more about how to use it with VITS (and maybe Fastspeech 2 also)?
Thank you.

**Comment by yl4579** [comment]
For VITS, you can just replace the [embedding in text encoder](https://github.com/jaywalnut310/vits/blob/main/models.py#L155) with the output of PL-BERT, and nothing else needs to be changed. For FastSpeech 2, you can replace the [encoder](https://github.com/ming024/FastSpeech2/blob/master/model/fastspeech2.py#L20) with PL-BERT with the same hidden channels (768), or you can append a linear projection same as used in StyleTTS.
